Repository DataDog/dd-agent, pull requests merged in 2018-05, with the labels that each got.

#3737 [changelog] Add entry for 5.24.0
  CHANGELOG.md
Labels: documentation

#3738 Fix source install for integrations base pkg name change
  packaging/datadog-agent/source/setup_agent.sh
Labels: bugfix, packaging

#3739 [source install] 5.24.0
  packaging/datadog-agent/source/setup_agent.sh
Labels: packaging

#3729 Make the classpath seperator in jmxfetch adjust to the os
  jmxfetch.py
Labels: bugfix, community, windows

#3733 [IO] Fix on newer versions of iostat + tests + misc fix
  checks/system/unix.py
  tests/checks/mock/test_sysstat.py
Labels: bugfix
